#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ColorList.Resource", IsApplication=true)]

namespace ColorList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int colors = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorsEN = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int colorsET = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int inimesed = 2130968579;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int button1 = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int button10 = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int button2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int button4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int button5 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int button6 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int button7 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int button8 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int button9 = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int eesti = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int inglise = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int järgmine = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int relativeLayout1 = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Language = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RelativeLayoutt = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int Andreas = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
